# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# File.open("cop-data.rb", "w") do |file|
# 	iterator = 1
# 	File.open("cop-data.txt").readlines.each do |line|
# 		name_and_badge = line.split("OFFICER ").pop.split(",")
# 		name = name_and_badge.first.split(" ").map(&:downcase).map(&:capitalize).join(" ")
# 		badge = name_and_badge.last.split("#").last.strip
# 		file.puts "cop#{iterator} = Cop.create({:name => \"#{name}\", :badge_number => \"#{badge}\"})"
# 		unless iterator % 3 == 0
# 			precinct_id = Random.new.rand(123)
# 			file.puts "cop#{iterator}.update({:precinct_id => #{precinct_id}})" 
# 		end
# 		iterator += 1
# 	end
# end

(1..123).each do |precinct_id|
	Precinct.create({:number => precinct_id})
end

cop1 = Cop.create({:name => "Frederick Sawyer", :badge_number => "2576"})
cop1.update({:precinct_id => 45})
cop2 = Cop.create({:name => "Kurt Duncan", :badge_number => "2483"})
cop2.update({:precinct_id => 40})
cop3 = Cop.create({:name => "Shantel James", :badge_number => "3004"})
cop4 = Cop.create({:name => "Michael O’keefe", :badge_number => "26019"})
cop4.update({:precinct_id => 50})
cop5 = Cop.create({:name => "Thomas Lobello", :badge_number => "21193"})
cop5.update({:precinct_id => 12})
cop6 = Cop.create({:name => "Charles Brown", :badge_number => "949"})
cop7 = Cop.create({:name => "Terel Anderson", :badge_number => "03814"})
cop7.update({:precinct_id => 23})

cop8 = Cop.create({:name => "Kevin Rooney", :badge_number => "6778"})
cop8.update({:precinct_id => 122})
cop8.comments.build({:title => "What a Jerk", :author => "Carlton Banks", :text => "So I was driving my wife to the hospital and she was in active labor. We wanted to have a natural birth at home but when her water broke I slipped in the puddle and broke my wrist so she had to drive me to the hospital. Anyway this cop stops us and he's just laughing at me and being very VERY rude. Totally not cool. Then he gave my wife his phone number and told her that if she needs any help taking care of the baby she should call him."})
cop8.ratings.build({:courtesy => 2, :professionalism => 1, :respect => 2})
cop8.ratings.build({:courtesy => 3, :professionalism => 2, :respect => 2})


cop9 = Cop.create({:name => "Jose Ortiz", :badge_number => "7879"})
cop10 = Cop.create({:name => "Fnu Dellevalle", :badge_number => "6830"})
cop10.update({:precinct_id => 94})
cop11 = Cop.create({:name => "Kenneth Wagner", :badge_number => "28519"})
cop11.update({:precinct_id => 83})
cop12 = Cop.create({:name => "John Warren", :badge_number => "13763"})
cop13 = Cop.create({:name => "Joseph Schinz", :badge_number => "21951"})
cop13.update({:precinct_id => 82})
cop14 = Cop.create({:name => "Raymond Ng", :badge_number => "21793"})
cop14.update({:precinct_id => 52})
cop15 = Cop.create({:name => "Anthony Difrancesca", :badge_number => "4200"})
cop16 = Cop.create({:name => "Juan Berrio", :badge_number => "28430"})
cop16.update({:precinct_id => 66})
cop17 = Cop.create({:name => "Joann Spreen", :badge_number => "19464"})
cop17.update({:precinct_id => 42})
cop18 = Cop.create({:name => "Jose Torres", :badge_number => "11394"})
cop19 = Cop.create({:name => "James Zavala", :badge_number => "05726"})
cop19.update({:precinct_id => 70})
cop20 = Cop.create({:name => "Arthur Clarke", :badge_number => "8001"})
cop20.update({:precinct_id => 46})
cop21 = Cop.create({:name => "Michael Gerbasi", :badge_number => "20502"})
cop22 = Cop.create({:name => "Charles Murphy", :badge_number => "31615"})
cop22.update({:precinct_id => 0})
cop23 = Cop.create({:name => "Joseph Woodley", :badge_number => "12116"})
cop23.update({:precinct_id => 18})
cop24 = Cop.create({:name => "Paul Albano", :badge_number => "26129"})
cop25 = Cop.create({:name => "Jordan Mazur", :badge_number => "06497"})
cop25.update({:precinct_id => 75})
cop26 = Cop.create({:name => "Jamell Kendrick", :badge_number => "28700"})
cop26.update({:precinct_id => 3})
cop27 = Cop.create({:name => "Honman Yan", :badge_number => "31946"})
cop28 = Cop.create({:name => "Eugene Hackett", :badge_number => "21155"})
cop28.update({:precinct_id => 111})
cop29 = Cop.create({:name => "John Luongo", :badge_number => "00777"})
cop29.update({:precinct_id => 95})
cop30 = Cop.create({:name => "Mohammad Aryakia", :badge_number => "01705"})
cop31 = Cop.create({:name => "Kathleen Curnyn", :badge_number => "04318"})
cop31.update({:precinct_id => 31})
cop32 = Cop.create({:name => "Steven Valentine", :badge_number => "13585"})
cop32.update({:precinct_id => 120})
cop33 = Cop.create({:name => "Fnu Acosta", :badge_number => "20660"})
cop34 = Cop.create({:name => "Anthony Anzalone", :badge_number => "04699"})
cop34.update({:precinct_id => 39})
cop35 = Cop.create({:name => "Eric Albrecht", :badge_number => "15016"})
cop35.update({:precinct_id => 69})
cop36 = Cop.create({:name => "Brenda Bacote", :badge_number => "00167"})
cop37 = Cop.create({:name => "Shuhel Subhan", :badge_number => "240099"})
cop37.update({:precinct_id => 20})
cop38 = Cop.create({:name => "Louis Chiaccheri", :badge_number => "02786"})
cop38.update({:precinct_id => 51})
cop39 = Cop.create({:name => "Lisa Riddick", :badge_number => "11944"})
cop40 = Cop.create({:name => "Chichoi Bao", :badge_number => "16456"})
cop40.update({:precinct_id => 95})
cop41 = Cop.create({:name => "Tamar Uster", :badge_number => "10517"})
cop41.update({:precinct_id => 78})
cop42 = Cop.create({:name => "Diana Gayo", :badge_number => "25146"})
cop43 = Cop.create({:name => "Richard Lavelle", :badge_number => "2384"})
cop43.update({:precinct_id => 80})
cop44 = Cop.create({:name => "Marlon George", :badge_number => "19193"})
cop44.update({:precinct_id => 70})
cop45 = Cop.create({:name => "Martin Gimenez", :badge_number => "22916"})
cop46 = Cop.create({:name => "Sandra Deleonmoya", :badge_number => "27876"})
cop46.update({:precinct_id => 80})
cop47 = Cop.create({:name => "Graham Emburey", :badge_number => "25748"})
cop47.update({:precinct_id => 39})
cop48 = Cop.create({:name => "Fnu Cordon", :badge_number => "25605"})
cop49 = Cop.create({:name => "Joseph John", :badge_number => "2797"})
cop49.update({:precinct_id => 110})
cop50 = Cop.create({:name => "David Hung", :badge_number => "19904"})
cop50.update({:precinct_id => 29})
cop51 = Cop.create({:name => "Santiago Gomez", :badge_number => "19288"})
cop52 = Cop.create({:name => "Fnu O'dougherty", :badge_number => "13510"})
cop52.update({:precinct_id => 51})
cop53 = Cop.create({:name => "David Poplaski", :badge_number => "15482"})
cop53.update({:precinct_id => 83})
cop54 = Cop.create({:name => "Fnu Diaz", :badge_number => "24459"})
cop55 = Cop.create({:name => "Joann Spreen", :badge_number => "19464"})
cop55.update({:precinct_id => 113})
cop56 = Cop.create({:name => "Vincent Fiore", :badge_number => "25517"})
cop56.update({:precinct_id => 65})
cop57 = Cop.create({:name => "John Coyle", :badge_number => "2031"})
cop58 = Cop.create({:name => "Honmanyan", :badge_number => "31945"})
cop58.update({:precinct_id => 8})
cop59 = Cop.create({:name => "Arthur Clarke", :badge_number => "80001"})
cop59.update({:precinct_id => 122})
cop60 = Cop.create({:name => "Anthony Susi", :badge_number => "31162"})
cop61 = Cop.create({:name => "Eddie Perez", :badge_number => "22433"})
cop61.update({:precinct_id => 64})
cop62 = Cop.create({:name => "Donald Gessner", :badge_number => "00261"})
cop62.update({:precinct_id => 35})
cop63 = Cop.create({:name => "Benjamin Bellinger", :badge_number => "25108"})
cop64 = Cop.create({:name => "Marc Richardson", :badge_number => "21396"})
cop64.update({:precinct_id => 93})
cop65 = Cop.create({:name => "Robertstokes", :badge_number => "18187"})
cop65.update({:precinct_id => 69})
cop66 = Cop.create({:name => "66. Nypd Sergeant Richard Johnson", :badge_number => "00759"})
cop67 = Cop.create({:name => "Edward Marcial", :badge_number => "13689"})
cop67.update({:precinct_id => 72})
cop68 = Cop.create({:name => "Marcy Garcia", :badge_number => "17029"})
cop68.update({:precinct_id => 12})
cop69 = Cop.create({:name => "Vincent Gallo", :badge_number => "19958"})
cop70 = Cop.create({:name => "William Gross", :badge_number => "26890"})
cop70.update({:precinct_id => 42})
cop71 = Cop.create({:name => "Leo Nugent", :badge_number => "11654"})
cop71.update({:precinct_id => 118})
cop72 = Cop.create({:name => "Steven Valentine", :badge_number => "13585"})
cop73 = Cop.create({:name => "Abraham Arteaga", :badge_number => "27115"})
cop73.update({:precinct_id => 87})
cop74 = Cop.create({:name => "John Mcgowan", :badge_number => "13466"})
cop74.update({:precinct_id => 27})
cop75 = Cop.create({:name => "Vincent Gallo", :badge_number => "19958"})
cop76 = Cop.create({:name => "Lisa Rodriguez", :badge_number => "8788"})
cop76.update({:precinct_id => 84})
cop77 = Cop.create({:name => "David Szabolcs", :badge_number => "12180"})
cop77.update({:precinct_id => 41})
cop78 = Cop.create({:name => "Fnu Wallace", :badge_number => "1194"})
cop79 = Cop.create({:name => "Steven Valentine", :badge_number => "13585"})
cop79.update({:precinct_id => 74})
cop80 = Cop.create({:name => "Brendan Beyrer", :badge_number => "18723"})
cop80.update({:precinct_id => 10})
cop81 = Cop.create({:name => "Joseph Castro", :badge_number => "05318"})
cop82 = Cop.create({:name => "Daniel Groth", :badge_number => "23788"})
cop82.update({:precinct_id => 94})
cop83 = Cop.create({:name => "Keith Foster", :badge_number => "08578"})
cop83.update({:precinct_id => 63})
cop84 = Cop.create({:name => "Eddie Perez", :badge_number => "22433"})
cop85 = Cop.create({:name => "Vincent Gallo", :badge_number => "19958"})
cop85.update({:precinct_id => 102})
cop86 = Cop.create({:name => "John Coyle", :badge_number => "20321"})
cop86.update({:precinct_id => 30})
cop87 = Cop.create({:name => "Jamell Kendrick", :badge_number => "38700"})
cop88 = Cop.create({:name => "Kenneth Wagner", :badge_number => "28519"})
cop88.update({:precinct_id => 33})
cop89 = Cop.create({:name => "Naim Ibroci", :badge_number => "24725"})
cop89.update({:precinct_id => 50})
cop90 = Cop.create({:name => "William Grodnick", :badge_number => "04729"})
cop91 = Cop.create({:name => "Christop Timm", :badge_number => "06338"})
cop91.update({:precinct_id => 68})
cop92 = Cop.create({:name => "Sandy Gonzalez", :badge_number => "22997"})
cop92.update({:precinct_id => 82})
cop93 = Cop.create({:name => "Alberto Cornea", :badge_number => "06487"})
cop94 = Cop.create({:name => "Honman Yan", :badge_number => "31946"})
cop94.update({:precinct_id => 47})
cop95 = Cop.create({:name => "Ricardo Wyman", :badge_number => "27066"})
cop95.update({:precinct_id => 53})
cop96 = Cop.create({:name => "Joann Spreen", :badge_number => "19464"})
cop97 = Cop.create({:name => "Frederic Pineda", :badge_number => "08502"})
cop97.update({:precinct_id => 8})
cop98 = Cop.create({:name => "John Coyle", :badge_number => "20321"})
cop98.update({:precinct_id => 88})
cop99 = Cop.create({:name => "Neil Rodriguez", :badge_number => "21015"})
cop100 = Cop.create({:name => "Anthony Difrancesca", :badge_number => "04200"})
cop100.update({:precinct_id => 45})


